# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pichaya Srifar
tagline:          'pichaya'
description:      'A programmer who try to change the world with his software'
url:              http://pichaya.in.th

author:
  name:           'Pichaya Srifar'
  url:            https://twitter.com/pichayas

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/pichaya/pichaya.github.io
